version: 2

jobs:
  build:

  docker:
    - image: circleci/openjdk:8-jdk-browsers

  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Install nextflow
          command: 'curl -fsSL get.nextflow.io | bash'
      - run:
          name: Test
          command: './nextflow run . -with-docker'

