version: 2

jobs:
  build:

  docker:
    - image: circleci/openjdk:8-jdk-browsers

  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: get nextflow
          command: 'curl -fsSL get.nextflow.io | bash'
      - run:
          name: pipeline execution
          command: '- ./nextflow run . -with-docker'



#machine:
#  java:
#    version: openjdk8
#  services:
#    - docker
#
#test:
#  override:
#    - curl -fsSL get.nextflow.io | bash
#    - ./nextflow run . -with-docker :
#        timeout: 1200
