version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: mkdir test
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Test
          command: curl -fsSL get.nextflow.io | bash
      - run:
          name: Generate code coverage
          command: ./nextflow run . -with-docker
