version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Test mkdir
          command: mkdir test
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Test
          command: curl -fsSL get.nextflow.io | bash
      - run:
          name: Generate code coverage
          command: ./nextflow run . -with-docker

  workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
