version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201703-01
    steps:
      - checkout
      - run:
          name: Install Nextflow
          command: curl -fsSL get.nextflow.io | bash
  test:
      - checkout
      - run:
          name: Run Pipeline
          command: ./nextflow run . -with-docker

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
